apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: internal-api
  template:
    metadata:
      labels:
        app: internal-api
    spec:
      containers:
        - name: internal-api
          image: <your-dockerhub-username>/internal-api:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: internal-api
spec:
  selector:
    app: internal-api
  ports:
    - port: 8080
      targetPort: 8080
